--DROP TABLE TBL_USER CASCADE CONSTRAINTS;
--DROP TABLE TBL_CHARGING_BOOKMARK CASCADE CONSTRAINTS;
--DROP TABLE TBL_CHARGING_STATION CASCADE CONSTRAINTS;
--DROP TABLE TBL_GAS_STATION CASCADE CONSTRAINTS;
--DROP TABLE TBL_PRICEINFO CASCADE CONSTRAINTS;
--DROP TABLE TBL_REGION CASCADE CONSTRAINTS;
--DROP TABLE TBL_GAS_BOOKMARK CASCADE CONSTRAINTS;

CREATE TABLE TBL_USER (
	USER_ID	VARCHAR2(20)	NOT NULL,
	USER_PW	VARCHAR2(20)	NOT NULL,
	USER_NAME	VARCHAR2(20)	NOT NULL,
	USER_PHONE	VARCHAR2(50)	NOT NULL,
	USER_EMAIL	VARCHAR2(50)	NOT NULL,
	USER_POWER_TYPE	VARCHAR2(20)	CHECK(USER_POWER_TYPE IN ('G', 'C')) NULL,
    CONSTRAINT PK_USER_ID PRIMARY KEY (USER_ID)
);

CREATE TABLE TBL_CHARGING_STATION (
    C_STATION_ID   VARCHAR2(20)   NOT NULL,
    C_STATION_NAME   VARCHAR2(20)   NULL,
    C_STATION_ADDRESS   VARCHAR2(100)   NULL,
    C_ADDRDETAIL   VARCHAR2(100)   NULL,
    C_TIME   VARCHAR2(50)   NULL,
    C_MANAGEMENT   VARCHAR2(20)   NULL,
    C_STATION_TEL   VARCHAR2(50)   NULL,
    CHARGER_STAT   NUMBER   NULL,
    CHARGER_TYPE   NUMBER   NULL,
    REGION_CODE   NUMBER   NOT NULL,
    C_PARKINGFEE   VARCHAR2(20)   NULL,
    C_GUIDE   VARCHAR2(50)   NULL,
    CHARGING_CAPA   NUMBER   NULL,
    CHARGING_METHOD   VARCHAR2(20)   NULL,
    CONSTRAINT PK_C_STATION_ID PRIMARY KEY(C_STATION_ID)
);

CREATE TABLE TBL_CHARGING_BOOKMARK (
	BOOKMARK_NO	VARCHAR2(20)	NULL,
	USER_ID	VARCHAR2(20)	NULL,
	C_STATION_ID	VARCHAR2(20)	NULL,
    CONSTRAINT PK_C_BOOKMARK_NO PRIMARY KEY (BOOKMARK_NO),
    CONSTRAINT FK_C_USER_ID FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
    CONSTRAINT FK_C_STATION_ID FOREIGN KEY(C_STATION_ID) REFERENCES TBL_CHARGING_STATION(C_STATION_ID)
);

CREATE TABLE TBL_GAS_STATION (
    	G_STATION_ID VARCHAR2(20)	NOT NULL,
	G_STATION_TRADEMARK	VARCHAR2(20)	NULL,
	G_STATION_NAME	VARCHAR2(20)	NOT NULL,
	G_STATION_ADDRESS	VARCHAR2(100)	NOT NULL,
	G_STATION_TEL	VARCHAR2(50)	NOT NULL,
	REGION_CODE	NUMBER 		NOT NULL,
	MAINT_YN	VARCHAR2(20)	NULL,
	WASH_YN	VARCHAR2(20)	NULL,
	CVS_YN	VARCHAR2(20)	NULL,
	GASOLINE_PRICE	NUMBER 		NOT NULL,
	DIESEL_PRICE	NUMBER 		NOT NULL,
    CONSTRAINT PK_G_STATION_ID PRIMARY KEY (G_STATION_ID)
);

CREATE TABLE TBL_GAS_BOOKMARK (
	BOOKMARK_NO	VARCHAR2(20)	NULL,
	USER_ID	VARCHAR2(20)	NULL,
	G_STATION_ID	VARCHAR2(20)	NULL,
    CONSTRAINT PK_G_BOOKMARK_NO PRIMARY KEY (BOOKMARK_NO),
    CONSTRAINT FK_G_USER_ID FOREIGN KEY(USER_ID) REFERENCES TBL_USER(USER_ID),
    CONSTRAINT FK_G_STATION_ID FOREIGN KEY(G_STATION_ID) REFERENCES TBL_GAS_STATION(G_STATION_ID)
);

CREATE TABLE TBL_REGION (
	REGION_CODE	NUMBER		NOT NULL,
	REGION_NAME	VARCHAR2(20)	NOT NULL,
    CONSTRAINT PK_REGION_CODE PRIMARY KEY (REGION_CODE)
);

CREATE TABLE TBL_PRICEINFO (
	REGION_CODE	NUMBER		NOT NULL,
	DIESEL_MIN	VARCHAR2(20)	NOT NULL,
	GASOLINE_MIN VARCHAR2(20)	NOT NULL,
	DIESEL_AVG	VARCHAR2(20)	NOT NULL,
	GASOLINE_AVG VARCHAR2(20)	NOT NULL,
	REGION_NAME	VARCHAR2(20)	NOT NULL,
    CONSTRAINT PK_P_REGION_CODE PRIMARY KEY (REGION_CODE)
);

--충전소 테이블에 지역코드 컬럼을 FK설정
ALTER TABLE TBL_CHARGING_STATION ADD CONSTRAINT FK_C_REGION_CODE
FOREIGN KEY(REGION_CODE) REFERENCES TBL_REGION(REGION_CODE);

--주유소 테이블에 지역코드 컬럼을 FK설정
ALTER TABLE TBL_GAS_STATION ADD CONSTRAINT FK_G_REGION_CODE 
FOREIGN KEY(REGION_CODE) REFERENCES TBL_REGION(REGION_CODE);

--지역별 가격 테이블에 지역코드 컬럼을 FK설정
ALTER TABLE TBL_PRICEINFO ADD CONSTRAINT FK_P_REGION_CODE 
FOREIGN KEY(REGION_CODE) REFERENCES TBL_REGION(REGION_CODE);





---- PROMPT LOADING TBL_USER // 회원정보에 임시 데이터 삽입
INSERT ALL
INTO TBL_USER VALUES ('kh', 'hello1234', '홍길동', '010-1111-2222','kh@naver.com','G')
INTO TBL_USER VALUES ('codeit', 'hello1234', '최태영', '010-2222-3333','kh@gmail.com','C')
INTO TBL_USER VALUES ('programmer', 'hello1234', '이수영', '010-3333-4444','kh@daum.net','C')
SELECT * FROM DUAL;

---- PROMPT LOADING TBL_REGION //지역에 임시 데이터 삽입
INSERT ALL
INTO TBL_REGION VALUES (01, '서울특별시')
INTO TBL_REGION VALUES (02, '인천광역시')
INTO TBL_REGION VALUES (03, '부산광역시')
INTO TBL_REGION VALUES (04, '경기도')
INTO TBL_REGION VALUES (05, '강원도')
SELECT * FROM DUAL;

---- PROMPT LOADING TBL_CHARGING_STATION //충전소에 임시 데이터 삽입
INSERT ALL
INTO TBL_CHARGING_STATION VALUES ('C125445', '양주충전소', '경기도 양주시 광사동 233동', '사거리 앞', '24시간 이용 가능', '오토맨', '02-420-1122', 1, 01, 01, 'Y', '공사로 인해 불가', 300, '단독')
SELECT * FROM DUAL;

---- PROMPT LOADING TBL_GAS_STATION //주유소에 임시 데이터 삽입
INSERT ALL
INTO TBL_GAS_STATION VALUES ('G125445', 'GS칼텍스', '양주주유소', '경기도 양주시 광사동 233동', '02-420-1122', '04', 'Y', 'Y', 'Y', '1870', '1500')
INTO TBL_GAS_STATION VALUES ('G258958', 'S-OIL', '서울주유소', '서울특별시 강남구 233로', '02-482-4455', '01', 'Y', 'Y', 'N', '1900', '1400')
INTO TBL_GAS_STATION VALUES ('G698257', 'SK에너지', '부산주유소', '부산광역시 사하로길 14', '02-5895-8658', '03', 'N', 'Y', 'N', '2144', '1800')
SELECT * FROM DUAL;

---- PROMPT LOADING TBL_PRICEINFO // 지역별가격 임시 데이터 삽입(생략)
INSERT INTO TBL_PRICEINFO (REGION_CODE, DIESEL_MIN, GASOLINE_MIN, DIESEL_AVG, GASOLINE_AVG, REGION_NAME)
VALUES (01, '1231', '1233', '1212', '1211', '서울특별시');


---- PROMPT LOADING TBL_STATION_BOOKMARK //즐겨찾기 주유소 임시 데이터 삽입(생략)
INSERT INTO TBL_GAS_BOOKMARK (BOOKMARK_NO, USER_ID, G_STATION_ID)
VALUES ('1', 'kh', 'G125445');

---- PROMPT LOADING TBL_STATION_BOOKMARK //즐겨찾기 충전소 임시 데이터 삽입(생략)
INSERT INTO TBL_CHARGING_BOOKMARK (BOOKMARK_NO, USER_ID, C_STATION_ID)
VALUES ('1', 'kh', 'C125445');



COMMIT;